INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:24:04] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:29] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:32] "[32mPOST /login HTTP/1.1[0m" 302 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:32] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:35] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:36] "[32mPOST /login HTTP/1.1[0m" 302 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:36] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:31:50] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:16] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:18] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:18] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:18] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:19] "[32mPOST /login HTTP/1.1[0m" 302 -
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:19] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:32:24] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on / [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 10, in inicio
    return render_template('inico.html')
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 146, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1081, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\jinja2\loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 62, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\templating.py", line 98, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: inico.html
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:37:18] "[35m[1mGET / HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:39:56] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:39:57] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [21/Mar/2023 07:39:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:16:07] "GET / HTTP/1.1" 200 -
ERROR:app:Exception on /juego [POST]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 26, in insertarJuego
    nombre = body["nombre"]
KeyError: 'nombre'
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:18:16] "[35m[1mPOST /juego HTTP/1.1[0m" 500 -
ERROR:app:Exception on /juego [POST]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 26, in insertarJuego
    nombre = body["nombre"]
KeyError: 'nombre'
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:18:44] "[35m[1mPOST /juego HTTP/1.1[0m" 500 -
ERROR:app:Exception on /juego [POST]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 26, in insertarJuego
    nombre = body["nombre"]
KeyError: 'nombre'
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:22:40] "[35m[1mPOST /juego HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
ERROR:app:Exception on /juego/1 [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'obtenerJuego' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:23:10] "[35m[1mGET /juego/1 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /juego/1 [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'obtenerJuego' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:23:48] "[35m[1mGET /juego/1 HTTP/1.1[0m" 500 -
ERROR:app:Exception on /juego [POST]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 26, in insertarJuego
    nombre = body["nombre"]
KeyError: 'nombre'
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:25:01] "[35m[1mPOST /juego HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:27:26] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:27:40] "POST /juego HTTP/1.1" 200 -
ERROR:app:Exception on /juego/1 [GET]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1826, in full_dispatch_request
    return self.finalize_request(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1845, in finalize_request
    response = self.make_response(rv)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2137, in make_response
    raise TypeError(
TypeError: The view function for 'obtenerJuego' did not return a valid response. The function either returned None or ended without a return statement.
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:27:48] "[35m[1mGET /juego/1 HTTP/1.1[0m" 500 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:29:55] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:29:55] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:29:55] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:32:53] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:32:53] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:32:54] "GET /login HTTP/1.1" 200 -
ERROR:app:Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Python\BD\FLASK\app.py", line 20, in login
    session["username"]=usuario
  File "C:\Python\BD\FLASK\.venv\lib\site-packages\flask\sessions.py", line 98, in _fail
    raise RuntimeError(
RuntimeError: The session is unavailable because no secret key was set.  Set the secret_key on the application to something unique and secret.
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:33:01] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:33:14] "GET /juego/1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:33:34] "[31m[1mGET /juego HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:33:50] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:35:39] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:35:40] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:35:45] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:05] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:05] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:18] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:20] "[32mPOST /login HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:20] "GET / HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:36:57] "GET / HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:38:20] "[32mGET /salir HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:38:20] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:38:26] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:38:26] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:39:22] "GET /juego/0 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:39:29] "GET /juego/1 HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:42:48] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:43:24] "[31m[1mPOST /juego/1 HTTP/1.1[0m" 405 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:43:32] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:44:26] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 07:44:57] "POST /juego HTTP/1.1" 200 -
INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 17:35:47] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 17:35:47] "GET /login HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 17:35:50] "[33mGET /lugar HTTP/1.1[0m" 404 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 17:35:50] "GET /static/404.css HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [22/Mar/2023 17:35:50] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
